language: node_js
node_js:
- '10'
script:
- npm run travis-test
deploy:
  provider: npm
  email: julien.ducro@deskpro.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
